# -*- coding: utf-8 -*-
"""svm clf.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bE1d61kAGWuPi3J-m1g9mGv8pL8435jZ
"""


from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

file_pathtr ='/content/drive/MyDrive/NSL-KDD dataset/KDDTrain+.txt'
train_data = pd.read_csv(file_pathtr, header=None)
file_pathte='/content/drive/MyDrive/NSL-KDD dataset/KDDTest+.txt'
test_data = pd.read_csv(file_pathte, header=None)

column_names = ['duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes', 'land', 'wrong_fragment',
                'urgent', 'hot', 'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell', 'su_attempted', 
                'num_root', 'num_file_creations', 'num_shells', 'num_access_files', 'num_outbound_cmds', 'is_host_login',
                'is_guest_login', 'count', 'srv_count', 'serror_rate', 'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 
                'same_srv_rate', 'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count','dst_host_srv_count',
                'dst_host_same_srv_rate', 'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate', 
                'dst_host_serror_rate', 'dst_host_srv_serror_rate', 'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 'label', 'duration']

train_data.columns = column_names
test_data.columns = column_names

train_data.head()
test_data.head()

X_train = train_data.drop('label', axis=1)
y_train = train_data['label']
X_test = test_data.drop('label', axis=1)
y_test = test_data['label']

X_train = pd.get_dummies(X_train, columns=['protocol_type', 'service', 'flag'])
X_test = pd.get_dummies(X_test, columns=['protocol_type', 'service', 'flag'])

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

from sklearn.preprocessing import LabelEncoder
def le(df):
    df = pd.DataFrame(df)  
    for col in df.columns:
        if df[col].dtype == 'object':
            label_encoder = LabelEncoder()
            df[col] = label_encoder.fit_transform(df[col])
    return df.values  
le(X_train)
le(X_test)

X_train_df = pd.DataFrame(X_train)
X_test_df = pd.DataFrame(X_test)
test_cols = set(X_train_df.columns)
train_cols = set(X_test_df.columns)
missing_cols = train_cols.difference(test_cols)
extra_cols = test_cols.difference(train_cols)
print("Missing columns:", missing_cols)
print("Extra columns:", extra_cols)
for col in missing_cols:
    X_test_df[col] = 0
X_test_df.fillna(0, inplace=True)
for col in extra_cols:
  if col in X_train_df.columns:
    X_train_df.drop(col, axis=1, inplace=True)

from sklearn.feature_selection import RFE
import itertools

svm_clf = SVC(kernel='linear', C=11.9, random_state=42, gamma=0.01)
svm_clf.fit(X_train_df, y_train)

rfe = RFE(svm_clf, n_features_to_select=10)
rfe = rfe.fit(X_train_df, y_train)

feature_map = [(i, v) for i, v in itertools.zip_longest(rfe.support_, X_train.columns)]
selected_features = [v for i, v in feature_map if i]

y_pred = svm_clf.predict(X_test_df)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("Accuracy Score:")
print(accuracy_score(y_test, y_pred))
from sklearn.metrics import f1_score, precision_score, recall_score
f= f1_score(y_test, y_pred,average="micro")
p= precision_score(y_test, y_pred,average="weighted",zero_division=1.0)
r= recall_score(y_test, y_pred,average="weighted",zero_division=1.0)
print("f1_score = ",f)
print("Precision Score = ",p)
print("recall score = ",r)

from sklearn.metrics import classification_report
print("SVM Classifier:")
print(classification_report(y_test, y_pred))

import joblib
import pickle 
joblib.dump(svm_clf, "svm.pkl")